# Generated by Django 2.2.4 on 2019-08-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='in_stock',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='picture',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
