# Generated by Django 2.2.4 on 2019-08-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_auto_20190826_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='picture',
            field=models.ImageField(upload_to='commodity'),
        ),
    ]
