# Generated by Django 2.2.4 on 2019-08-26 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodity', '0002_auto_20190826_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('hall', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=10)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.Commodity')),
            ],
        ),
    ]
