# Generated by Django 2.2.4 on 2019-08-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client_name',
            new_name='name',
        ),
    ]
