# Generated by Django 2.2.4 on 2019-08-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190827_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='fullname',
        ),
    ]
