# Generated by Django 2.2.4 on 2019-08-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190827_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contact',
            new_name='telephone',
        ),
    ]
