# Generated by Django 2.2.4 on 2019-08-28 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_auto_20190826_1828'),
        ('order', '0004_auto_20190827_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('hall', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=10)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.Commodity')),
            ],
        ),
    ]
